name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy on EC2 with Docker
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app || git clone https://github.com/<your-username>/<your-repo>.git ~/app
            cd ~/app
            git pull origin main
            # Build docker image
            docker build -t myapp .
            # Stop old container (if running)
            docker rm -f myapp-container || true
            # Run new container
            docker run -d --name myapp-container -p 80:80 myapp
          EOF
